/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Users.Product;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Objects;

import static GUI.LoginFrame.Products;

/**
 *
 * @author Mohamed Kandeel
 */
public class InventoryConsole extends javax.swing.JFrame {

    /**
     * Creates new form InventoryConsole
     */
    public InventoryConsole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTableInventory = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reportLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Inventory Dashboard");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        listButton.setText("List");
        listButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listButtonMouseClicked(evt);
            }
        });

        productsTableInventory.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Price", "Expriry Date", "Quantity", "Discount", "Category"
                }
        ));
        productsTableInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsTableInventoryMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(productsTableInventory);

        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Report from Marketing Team:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(222, 222, 222)
                                                                .addComponent(jLabel1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(addButton)
                                                                                .addGap(82, 82, 82)
                                                                                .addComponent(updateButton)
                                                                                .addGap(123, 123, 123)
                                                                                .addComponent(deleteButton))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(reportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(listButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(61, 61, 61))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchButton))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addButton)
                                        .addComponent(updateButton)
                                        .addComponent(deleteButton)
                                        .addComponent(listButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(reportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {
        DefaultTableModel tableModel = (DefaultTableModel) productsTableInventory.getModel();
        tableModel.addRow(new Object[]{});
    }

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {
        String[] rowData = new String[8];
        DefaultTableModel productsTableInventoryModel = (DefaultTableModel) productsTableInventory.getModel();

        for (int i = 0; i < productsTableInventoryModel.getRowCount(); i++) {
            for (int j = 0; j < 7; j++) {
                rowData[j] = String.valueOf(productsTableInventoryModel.getValueAt(i, j));
            }
            for (Product product: Products){
                if (Objects.equals(rowData[0], String.valueOf(product.getID()))){
                    rowData[7] = product.getReport();
                    break;
                }
            }
            String s = rowData[0] + ',' + rowData[1] + ',' + rowData[2] + ',' + rowData[3]
                    + ',' + rowData[4] + ',' + rowData[5] + ',' + rowData[6] + ',' + rowData[7];
            if (i == 0)
                FileOperations.write(s, "products.txt", false);
            else FileOperations.write(s, "products.txt", true);
        }
    }

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {
        DefaultTableModel productsTableInventoryModel = (DefaultTableModel) productsTableInventory.getModel();
        if (productsTableInventory.getSelectedRow() != -1)
            productsTableInventoryModel.removeRow(productsTableInventory.getSelectedRow());
    }

    private void listButtonMouseClicked(java.awt.event.MouseEvent evt) {
        Products = (ArrayList<Product>) (Object) FileOperations.read("products.txt");
        DefaultTableModel tableModel = (DefaultTableModel) productsTableInventory.getModel();
        tableModel.setRowCount(0);
        for (Product product: Products) {
            Object rowData[] = {String.valueOf(product.getID()), product.getName(), product.getPrice(), product.getExpireDate(),
                    product.getQuantity(), product.getDiscount(), product.getCategory()};
            tableModel.addRow(rowData);
            if( product.getQuantity()<15) {
                String prompt_message = product.getName() + "'s quantity is " + product.getQuantity() + " (lower than 15)";

                JOptionPane.showMessageDialog(null, prompt_message);
            }
        }
    }

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {
        Products = (ArrayList<Product>) (Object) FileOperations.read("products.txt");
        for (Product product: Products){
            if (Objects.equals(searchTextField.getText(), String.valueOf(product.getID())) ||
                    Objects.equals(searchTextField.getText(), product.getName())){
                DefaultTableModel tableModel = (DefaultTableModel) productsTableInventory.getModel();
                tableModel.setRowCount(0);
                Object rowData[] = {String.valueOf(product.getID()), product.getName(), product.getPrice(), product.getExpireDate(),
                        product.getQuantity(), product.getDiscount(), product.getCategory()};
                tableModel.addRow(rowData);
                reportLabel.setText(product.getReport());
                break;
            }
        }
    }

    private void productsTableInventoryMouseClicked(java.awt.event.MouseEvent evt) {
        DefaultTableModel productsModel = (DefaultTableModel) productsTableInventory.getModel();
        int selectedRow = productsTableInventory.getSelectedRow();
        int selectedID = Integer.parseInt(String.valueOf(productsModel.getValueAt(selectedRow, 0)));
        for (Product product: Products){
            if (selectedID == product.getID()){
                reportLabel.setText(product.getReport());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listButton;
    private javax.swing.JTable productsTableInventory;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration
}
